package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u311/1894/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, September 27, 2021 5:16:48 AM PDT
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
	 * The value representing ID_UNIQUENESS_POLICY_ID.
	 */
  public static final int value = (int)(18L);
}
