package org.omg.PortableServer;


/**
* org/omg/PortableServer/IdUniquenessPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u311/1894/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, September 27, 2021 5:16:48 AM PDT
*/


/**
	 * The IdUniquenessPolicy specifies whether the servants 
	 * activated in the created POA must have unique object i
	 * identities. The default is UNIQUE_ID.
	 */
public interface IdUniquenessPolicy extends IdUniquenessPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdUniquenessPolicy
