package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynValueCommon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u311/1894/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Monday, September 27, 2021 5:16:46 AM PDT
*/


/**
    * DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
    */
public interface DynValueCommon extends DynValueCommonOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynValueCommon
