// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMsg.proto

package com.floweryu.netty.protobuf.bean;

public final class MsgProtos {
  private MsgProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.floweryu.netty.protobuf.bean.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string conetent = 2;</code>
     * @return The conetent.
     */
    java.lang.String getConetent();
    /**
     * <code>string conetent = 2;</code>
     * @return The bytes for conetent.
     */
    com.google.protobuf.ByteString
        getConetentBytes();
  }
  /**
   * Protobuf type {@code com.floweryu.netty.protobuf.bean.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.floweryu.netty.protobuf.bean.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      conetent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              conetent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.floweryu.netty.protobuf.bean.MsgProtos.internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.floweryu.netty.protobuf.bean.MsgProtos.internal_static_com_floweryu_netty_protobuf_bean_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.floweryu.netty.protobuf.bean.MsgProtos.Msg.class, com.floweryu.netty.protobuf.bean.MsgProtos.Msg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int CONETENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object conetent_;
    /**
     * <code>string conetent = 2;</code>
     * @return The conetent.
     */
    @java.lang.Override
    public java.lang.String getConetent() {
      java.lang.Object ref = conetent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conetent_ = s;
        return s;
      }
    }
    /**
     * <code>string conetent = 2;</code>
     * @return The bytes for conetent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConetentBytes() {
      java.lang.Object ref = conetent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conetent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conetent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conetent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conetent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conetent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.floweryu.netty.protobuf.bean.MsgProtos.Msg)) {
        return super.equals(obj);
      }
      com.floweryu.netty.protobuf.bean.MsgProtos.Msg other = (com.floweryu.netty.protobuf.bean.MsgProtos.Msg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getConetent()
          .equals(other.getConetent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CONETENT_FIELD_NUMBER;
      hash = (53 * hash) + getConetent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.floweryu.netty.protobuf.bean.MsgProtos.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.floweryu.netty.protobuf.bean.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.floweryu.netty.protobuf.bean.Msg)
        com.floweryu.netty.protobuf.bean.MsgProtos.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.floweryu.netty.protobuf.bean.MsgProtos.internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.floweryu.netty.protobuf.bean.MsgProtos.internal_static_com_floweryu_netty_protobuf_bean_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.floweryu.netty.protobuf.bean.MsgProtos.Msg.class, com.floweryu.netty.protobuf.bean.MsgProtos.Msg.Builder.class);
      }

      // Construct using com.floweryu.netty.protobuf.bean.MsgProtos.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        conetent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.floweryu.netty.protobuf.bean.MsgProtos.internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor;
      }

      @java.lang.Override
      public com.floweryu.netty.protobuf.bean.MsgProtos.Msg getDefaultInstanceForType() {
        return com.floweryu.netty.protobuf.bean.MsgProtos.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.floweryu.netty.protobuf.bean.MsgProtos.Msg build() {
        com.floweryu.netty.protobuf.bean.MsgProtos.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.floweryu.netty.protobuf.bean.MsgProtos.Msg buildPartial() {
        com.floweryu.netty.protobuf.bean.MsgProtos.Msg result = new com.floweryu.netty.protobuf.bean.MsgProtos.Msg(this);
        result.id_ = id_;
        result.conetent_ = conetent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.floweryu.netty.protobuf.bean.MsgProtos.Msg) {
          return mergeFrom((com.floweryu.netty.protobuf.bean.MsgProtos.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.floweryu.netty.protobuf.bean.MsgProtos.Msg other) {
        if (other == com.floweryu.netty.protobuf.bean.MsgProtos.Msg.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getConetent().isEmpty()) {
          conetent_ = other.conetent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.floweryu.netty.protobuf.bean.MsgProtos.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.floweryu.netty.protobuf.bean.MsgProtos.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object conetent_ = "";
      /**
       * <code>string conetent = 2;</code>
       * @return The conetent.
       */
      public java.lang.String getConetent() {
        java.lang.Object ref = conetent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conetent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string conetent = 2;</code>
       * @return The bytes for conetent.
       */
      public com.google.protobuf.ByteString
          getConetentBytes() {
        java.lang.Object ref = conetent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conetent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string conetent = 2;</code>
       * @param value The conetent to set.
       * @return This builder for chaining.
       */
      public Builder setConetent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conetent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string conetent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConetent() {
        
        conetent_ = getDefaultInstance().getConetent();
        onChanged();
        return this;
      }
      /**
       * <code>string conetent = 2;</code>
       * @param value The bytes for conetent to set.
       * @return This builder for chaining.
       */
      public Builder setConetentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        conetent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.floweryu.netty.protobuf.bean.Msg)
    }

    // @@protoc_insertion_point(class_scope:com.floweryu.netty.protobuf.bean.Msg)
    private static final com.floweryu.netty.protobuf.bean.MsgProtos.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.floweryu.netty.protobuf.bean.MsgProtos.Msg();
    }

    public static com.floweryu.netty.protobuf.bean.MsgProtos.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.floweryu.netty.protobuf.bean.MsgProtos.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_floweryu_netty_protobuf_bean_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ProtoMsg.proto\022 com.floweryu.netty.pro" +
      "tobuf.bean\"#\n\003Msg\022\n\n\002id\030\001 \001(\r\022\020\n\010coneten" +
      "t\030\002 \001(\tB-\n com.floweryu.netty.protobuf.b" +
      "eanB\tMsgProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_floweryu_netty_protobuf_bean_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_floweryu_netty_protobuf_bean_Msg_descriptor,
        new java.lang.String[] { "Id", "Conetent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
