server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_test?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /res/**
  web:
    resources:
      static-locations: classpath:/other/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
  
car:
  name: timi
  price: 111
  pet: 
    name: pig
    
person:
  username: zhangsan
#  animal: [cat, dog]
  animal:
    - cat
    - dog
#  score: {english: 80, math: 90}
  score:
    english: 80
    math: 90
  salarys: [999.9, 888.8]
  allPets:
    sick:
      - name: cat
        age: 8
      - {name: dog, age: 9}
    health: [{name: pig, age: 7}, {name: rabbit, age: 4}]
  
study:
  enabled: true